export const appConfig = {
    MEETINGROOM_INIT_WIDTH: 1000,
    MEETINGROOM_INIT_HEIGHT: 710,
    MEETINGROOM_CHAT_WIDTH: 1400,
    LOGIN_INIT_WIDTH: 375,
    LOGIN_INIT_HEIGHT: 400,
    REIGISTER_INIT_HEIGHT: 570,
    JOINMEETING_INIT_WIDTH: 370,
    JOINMEETING_INIT_HEIGHT: 500,
    HOME_INIT_WIDTH: 720,
    HOME_INIT_HEIGHT: 480
}